#!/bin/bash

#Parameters:

IlluminaBaseCallsToSam=$0
BASECALLS_DIR=$1
BARCODES_DIR=$2
LANE=$3
READ_STRUCTRUCTURE=$4
RUN_BARCODE=$5
LIBRARY_PARAMS=$6
TMP_DIR=$7
MOLECULAR_INDEX_TAG=$8
ADAPTERS_TO_CHECK="PAIRED_END"
TAG_PER_MOLECULAR_INDEX="ZA"



java -Xmx8g -jar $PICARD $IlluminaBaseCallsToSam \
		BASECALLS_DIR=$BASECALLS_DIR \
		BARCODES_DIR=$BARCODES_DIR \
		LANE=$LANE \
		READ_STRUCTRUCTURE=$READ_STRUCTRUCTURE \
		RUN_BARCODE=$RUN_BARCODE \
		LIBRARY_PARAMS=$LIBRARY_PARAMS \
		TMP_DIR=$TMP_DIR \
		MOLECULAR_INDEX_TAG=$MOLECULAR_INDEX_TAG \
		ADAPTERS_TO_CHECK=$ADAPTERS_TO_CHECK \

