#!/bin/bash

#Parameters:

ALIGNED=$1
UNMAPPED=$2
OUTPUT=$3
REFERENCE_SEQUENCE=$4
EXPECTED_ORIENTATION=$5
MAX_GAPS=$6
SORT_ORDER=$7
CREATE_INDEX=$8
ALIGNER_PROPER_PAIR_FLAGS=$9

java -Xmx4g -jar $PICARD MergeBanAlignment \
		ALIGNED=$ALIGNED \
		UNMAPPED=$UNMAPPED \
		OUTPUT=$OUTPUT \
		REFERENCE_SEQUENCE=$REFERENCE_SEQUENCE \
		EXPECTED_ORIENTATION=$EXPECTED_ORIENTATION \
		MAX_GAPS=$MAX_GAPS \
		SORT_ORDER=$SORT_ORDER \
		CREATE_INDEX=true \
		ALIGNER_PROPER_PAIR_FLAGS=false
