#!/bin/bash

#Parameters:


java -Xmx4g -jar $PICARD SamToFastq \
	INPUT=$INPUT \
	FASTQ=$FASTQ_1 \
	SECOND_END_FASTQ=$FASTQ_2 \
	INCLUDE_NON_PF_READS=false
	#CLIPPING_ATTRIBUTE=XT \
	#CLIPPING_ACTION=X \
	#CLIPPING_MIN_LENGTH=$CLIPPING_MIN_LENGTH
